title: J. M. L. Whittington's Critical Making Project Portfolio
description: A class exercise for ENG6819 â€” Critical Making for Humanist Scholarship, which features a webpage portfolio of critical making projects throughout the semester.
show_downloads: true
theme: jekyll-theme-minimal
